chore(lefthook): update config

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -1,58 +1,46 @@
-# EXAMPLE USAGE:
-#
-#   Refer for explanation to following link:
-#   https://lefthook.dev/configuration/
-#
-# pre-push:
-#   jobs:
-#     - name: packages audit
-#       tags:
-#         - frontend
-#         - security
-#       run: yarn audit
-#
-#     - name: gems audit
-#       tags:
-#         - backend
-#         - security
-#       run: bundle audit
-#
-# pre-commit:
-#   parallel: true
-#   jobs:
-#     - run: yarn eslint {staged_files}
-#       glob: "*.{js,ts,jsx,tsx}"
-#
-#     - name: rubocop
-#       glob: "*.rb"
-#       exclude:
-#         - config/application.rb
-#         - config/routes.rb
-#       run: bundle exec rubocop --force-exclusion {all_files}
-#
-#     - name: govet
-#       files: git ls-files -m
-#       glob: "*.go"
-#       run: go vet {files}
-#
-#     - script: "hello.js"
-#       runner: node
-#
-#     - script: "hello.go"
-#       runner: go run
-
 pre-commit:
-  jobs:
-    - name: format & lint
-      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
-      run: pnpm exec biome check --write --no-errors-on-unmatched --files-ignore-unknown=true --colors=off {staged_files}
-      stage_fixed: true
+  parallel: true
+  commands:
+    # affected:
+    #   run: pnpm nx show projects --affected
 
-    - name: lint
-      run: pnpm exec nx affected -t lint
+    # format:
+    #   run: pnpm nx format:write --files {staged_files}
+    #   stage_fixed: true
 
-    - name: test
-      run: pnpm exec nx affected -t test
+    lint:
+      run: pnpm nx run-many -t lint --outputStyle=stream
 
-    - name: build
-      run: pnpm exec nx affected -t build
+    test:
+      run: pnpm nx run-many -t test --parallel=1 --outputStyle=stream
+
+    build:
+      run: pnpm nx run-many -t build --parallel=1 --outputStyle=stream
+
+pre-push:
+  commands:
+    git-lfs:
+      run: |
+        command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
+        git lfs pre-push "$@"
+
+post-merge:
+  commands:
+    git-lfs:
+      run: |
+        command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-merge' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
+        git lfs post-merge "$@"
+
+post-commit:
+  commands:
+    git-lfs:
+      run: |
+        command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
+        git lfs post-commit "$@"
+
+post-checkout:
+  commands:
+    git-lfs:
+      run: |
+        command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-checkout' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
+        git lfs post-checkout "$@"
